services:
  - type: web
    name: prism-backend
    env: node
    rootDir: backend
    buildCommand: yarn install
    startCommand: yarn start
  - type: web
    name: prism-frontend
    env: node
    rootDir: frontend
    buildCommand: yarn install && yarn build
    startCommand: yarn start
