services:
  - type: web
    name: prism-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
  - type: web
    name: prism-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
