services:
  - type: web
    name: prism
    env: node
    buildCommand: |
      cd frontend && npm install --include=dev && npm run build
      cd backend && npm install
    startCommand: cd backend && npx ts-node src/index.ts